export const homeData = [
    {
      id: 1,
      name: "Bird Box",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://vejasp.abril.com.br/wp-content/uploads/2019/01/bird-box-netflix.png",
      video: "https://youtu.be/o2AsIXSh2xo",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "InterStaller",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Animation,Family",
      cover: "https://m.media-amazon.com/images/I/71GYzP6yw2L._AC_SX450_.jpg",
      video: "https://youtu.be/zSWdZVtXT7E",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Inception",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "https://cdn.mos.cms.futurecdn.net/N9nCdJHgqde57jcyAnd2KL-1200-80.jpg",
      video: "https://youtu.be/YoHD9XEInc0",
      date: "20-FEB-2010",
    },
    {
      id: 4,
      name: "Fractured",
      rating: 4.9,
      time: "2hr : 22mins",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "https://occ-0-1723-1009.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABfMp2rvUcdPYuPSMUMhk2kZlJn88aKQt_Tk7_hUzXtoxoXVFmy8r5qdpgU_9JnL8qFzHTU0auOgdPyWNbbzdJ9Pag678lqZ5CF_p.jpg?r=054",
      video: "https://youtu.be/S8obCz5NSog",
      date: "12-Aug-2015",
    },
  ]

  export const upcome = [
    {
      id: 1,
      cover: "https://occ-0-769-1123.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABQnQXWag1j8sxI_2jNtuHpkWAWlkq0siWBahygpdi9b-XOpKRj2ktxfMv9UzRxWKRl9uyKOf7x0mxfeCeQrhBPZOEcTES7Xl1bx-cUORBvJCyqS0c9zu9wvUe4q93VLkhl0cCA.jpg?r=a03",
      name: "Lupin",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "https://edebiyyat.az/uploads/posts/2020-04/1587567440_la-casa-de-papel-1024x723-1.jpg",
      name: "La casa de papel",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "https://i0.wp.com/mediianews.com/wp-content/uploads/2022/02/Is-Sherlock-Holmes-really-sociopathic-What-conditions-does-he-have.jpg?fit=2000%2C1000&ssl=1",
      name: "Sherlock Holmes",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "https://th-thumbnailer.cdn-si-edu.com/RXsWdq4u7JTjEnazw2rvBRTQYW0=/1072x720/filters:no_upscale():focal(634x85:635x86)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/7b/ba/7bba298e-7e2e-44f0-adb9-b47dfdc1e240/p05m69vt.jpg",
      name: "Peaky Blinders",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://www.refinery29.com/images/8449109.jpg?format=pjpg&auto=webp&resize-filter=lanczos2&quality=50&sharpen=a3%2Cr3%2Ct0&optimize=low&width=960&crop=5%3A6",
      name: "Friends",
      time: "2hr : 38mins",
    },
  ]

  export const uptrending = [
    {
      id: 1,
      cover: "https://m.media-amazon.com/images/M/MV5BNjRiYTIzZmUtMTFkNS00ZTM0LWE4ODAtMDliMGE4NzM5ZjVlXkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_.jpg",
      name: "The 100",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "https://occ.a.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABdc0wde_pmOSCSUY4rXeGjNd3fbA_KWXE_HhzHdcPtboFHxJ07_gOyWD1k7LonsQ2Oc630ACR5QiLiZq4MlUjowStfXqfPdpsWNS-89zz8bH0oWym3LYkoI0Gj1P_vYjy-wOvg.jpg?r=538",
      name: "The Rain",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "https://upload.wikimedia.org/wikipedia/tr/b/b5/Hakan_Muhaf%C4%B1z_afi%C5%9Fi.jpg",
      name: "Hakan Muhafız",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: "https://m.media-amazon.com/images/M/MV5BMWYxOTFlMjgtZTMyMS00OGRkLTk5ZGEtMDI2N2ZjN2EzZjg4XkEyXkFqcGdeQXVyMTIyMjI4OTkx._V1_FMjpg_UX1000_.jpg",
      name: "Kağıttan Hayatlar",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://www.heavenofhorror.com/wp-content/uploads/2020/04/into-the-night-netflix-review-season-1.jpg",
      name: "İnto The Night",
      time: "2hr : 38mins",
    },
  ]